<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_You have Successfully Subscribed_et_bl_d48585</name>
   <tag></tag>
   <elementGuidId>443c39be-0cdb-4953-962f-7682d51f742b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.et_bloom_close_button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6d853da3-812b-4ff0-b031-67bda948fee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>et_bloom_close_button</value>
      <webElementGuid>a2ebb83d-0f73-4dec-bd27-23accf54e9a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js&quot;]/body[@class=&quot;post-template-default single single-post postid-25946 single-format-standard custom-background et_bloom divi-100-article-card et_monarch et_color_scheme_green et_pb_button_helper_class et_fixed_nav et_show_nav et_cover_background et_secondary_nav_enabled et_secondary_nav_two_panels et_pb_gutter windows et_pb_gutters3 et_primary_nav_dropdown_animation_fade et_secondary_nav_dropdown_animation_fade et_pb_footer_columns3 et_header_style_left et_pb_pagebuilder_layout et_smooth_scroll et_full_width_page et_divi_theme et-db et_minified_js et_minified_css chrome&quot;]/div[@class=&quot;et_bloom_flyin et_bloom_optin et_bloom_resize et_bloom_flyin_right et_bloom_optin_1 et_bloom_trigger_bottom et_bloom_visible et_bloom_animated&quot;]/div[@class=&quot;et_bloom_form_container et_bloom_form_bottom with_edge carrot_edge et_bloom_stacked_flyin et_bloom_rounded et_bloom_form_text_dark et_bloom_animation_slideup et_flyin_1_field&quot;]/span[@class=&quot;et_bloom_close_button&quot;]</value>
      <webElementGuid>4a38733a-be63-4d9a-a19b-efd3f0a5680d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span</value>
      <webElementGuid>6fdd055d-8a7b-46f6-a5c8-98a085186b2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
